import Foundation

/// Represents a task/action item extracted from meeting minutes.
/// Tasks are generated by AI from uploaded Google Docs (Phase 5).
/// Named `MeetingTask` to avoid conflicts with Swift's Concurrency.Task.
struct MeetingTask: Identifiable, Codable, Equatable {
    // MARK: - Properties

    /// Unique identifier for the task
    let id: UUID

    /// Meeting ID where this task was generated
    let meetingId: UUID

    /// Organization ID for filtering tasks by organization
    let organizationId: UUID

    /// Task description/title
    let title: String

    /// User ID assigned to this task (extracted by AI, optional)
    var assigneeId: UUID?

    /// Task deadline if mentioned in meeting minutes (optional)
    var dueDate: Date?

    /// Whether the task has been completed
    var isCompleted: Bool

    /// When this task was created/extracted
    let createdAt: Date

    /// Source text from meeting minutes where task was extracted (optional)
    var extractedFrom: String?

    // MARK: - Initialization

    init(
        id: UUID = UUID(),
        meetingId: UUID,
        organizationId: UUID,
        title: String,
        assigneeId: UUID? = nil,
        dueDate: Date? = nil,
        isCompleted: Bool = false,
        createdAt: Date = Date(),
        extractedFrom: String? = nil
    ) {
        self.id = id
        self.meetingId = meetingId
        self.organizationId = organizationId
        self.title = title
        self.assigneeId = assigneeId
        self.dueDate = dueDate
        self.isCompleted = isCompleted
        self.createdAt = createdAt
        self.extractedFrom = extractedFrom
    }
}
